/* 
 * OBADA Client Helper API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Obada.Client.Client;
using Obada.Client.Api;
using Obada.Client.Model;

namespace Obada.Client.Test
{
    /// <summary>
    ///  Class for testing ObitApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ObitApiTests
    {
        private ObitApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ObitApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ObitApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' ObitApi
            //Assert.IsInstanceOf(typeof(ObitApi), instance);
        }

        
        /// <summary>
        /// Test DownloadObitFromChain
        /// </summary>
        [Test]
        public void DownloadObitFromChainTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ObitDid obitDid = null;
            //var response = instance.DownloadObitFromChain(obitDid);
            //Assert.IsInstanceOf(typeof(ClientObitResponse), response, "response is ClientObitResponse");
        }
        
        /// <summary>
        /// Test FetchObitFromChain
        /// </summary>
        [Test]
        public void FetchObitFromChainTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string obitDid = null;
            //var response = instance.FetchObitFromChain(obitDid);
            //Assert.IsInstanceOf(typeof(BlockChainObitResponse), response, "response is BlockChainObitResponse");
        }
        
        /// <summary>
        /// Test GenerateObitDef
        /// </summary>
        [Test]
        public void GenerateObitDefTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string manufacturer = null;
            //string partNumber = null;
            //string serialNumber = null;
            //var response = instance.GenerateObitDef(manufacturer, partNumber, serialNumber);
            //Assert.IsInstanceOf(typeof(ObitDefinitionResponse), response, "response is ObitDefinitionResponse");
        }
        
        /// <summary>
        /// Test GetClientObit
        /// </summary>
        [Test]
        public void GetClientObitTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string obitDid = null;
            //var response = instance.GetClientObit(obitDid);
            //Assert.IsInstanceOf(typeof(ClientObitResponse), response, "response is ClientObitResponse");
        }
        
        /// <summary>
        /// Test SaveClientObit
        /// </summary>
        [Test]
        public void SaveClientObitTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //LocalObit localObit = null;
            //var response = instance.SaveClientObit(localObit);
            //Assert.IsInstanceOf(typeof(ClientObitResponse), response, "response is ClientObitResponse");
        }
        
        /// <summary>
        /// Test UploadObit
        /// </summary>
        [Test]
        public void UploadObitTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ObitDid obitDid = null;
            //var response = instance.UploadObit(obitDid);
            //Assert.IsInstanceOf(typeof(BaseResponse), response, "response is BaseResponse");
        }
        
    }

}
