/*
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Obada.Client.Client;
using Obada.Client.Api;
using Obada.Client.Model;

namespace Obada.Client.Test
{
    /// <summary>
    ///  Class for testing UtilsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class UtilsApiTests
    {
        private UtilsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UtilsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UtilsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' UtilsApi
            //Assert.IsInstanceOf(typeof(UtilsApi), instance);
        }

        
        /// <summary>
        /// Test GenerateChecksum
        /// </summary>
        [Test]
        public void GenerateChecksumTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GenerateObitChecksumRequest generateObitChecksumRequest = null;
            //var response = instance.GenerateChecksum(generateObitChecksumRequest);
            //Assert.IsInstanceOf(typeof(GenerateObitChecksumResponse), response, "response is GenerateObitChecksumResponse");
        }
        
        /// <summary>
        /// Test GenerateDID
        /// </summary>
        [Test]
        public void GenerateDIDTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GenerateObitDIDRequest generateObitDIDRequest = null;
            //var response = instance.GenerateDID(generateObitDIDRequest);
            //Assert.IsInstanceOf(typeof(GenerateObitDIDResponse), response, "response is GenerateObitDIDResponse");
        }
        
    }

}
