/*
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Obada.Client.Api;
using Obada.Client.Model;
using Obada.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Obada.Client.Test
{
    /// <summary>
    ///  Class for testing Accounts
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountsTests
    {
        // TODO uncomment below to declare an instance variable for Accounts
        //private Accounts instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Accounts
            //instance = new Accounts();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Accounts
        /// </summary>
        [Test]
        public void AccountsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Accounts
            //Assert.IsInstanceOf(typeof(Accounts), instance);
        }


        /// <summary>
        /// Test the property 'HdAccounts'
        /// </summary>
        [Test]
        public void HdAccountsTest()
        {
            // TODO unit test for the property 'HdAccounts'
        }
        /// <summary>
        /// Test the property 'ImportedAccounts'
        /// </summary>
        [Test]
        public void ImportedAccountsTest()
        {
            // TODO unit test for the property 'ImportedAccounts'
        }

    }

}
