/* 
 * OBADA Client Helper API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Obada.Client.Api;
using Obada.Client.Model;
using Obada.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Obada.Client.Test
{
    /// <summary>
    ///  Class for testing BlockChainObitResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BlockChainObitResponseTests
    {
        // TODO uncomment below to declare an instance variable for BlockChainObitResponse
        //private BlockChainObitResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BlockChainObitResponse
            //instance = new BlockChainObitResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BlockChainObitResponse
        /// </summary>
        [Test]
        public void BlockChainObitResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" BlockChainObitResponse
            //Assert.IsInstanceOf(typeof(BlockChainObitResponse), instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'BlockchainObit'
        /// </summary>
        [Test]
        public void BlockchainObitTest()
        {
            // TODO unit test for the property 'BlockchainObit'
        }

    }

}
