/*
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Obada.Client.Api;
using Obada.Client.Model;
using Obada.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Obada.Client.Test
{
    /// <summary>
    ///  Class for testing DeviceDocument
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeviceDocumentTests
    {
        // TODO uncomment below to declare an instance variable for DeviceDocument
        //private DeviceDocument instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeviceDocument
            //instance = new DeviceDocument();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeviceDocument
        /// </summary>
        [Test]
        public void DeviceDocumentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DeviceDocument
            //Assert.IsInstanceOf(typeof(DeviceDocument), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DocumentFile'
        /// </summary>
        [Test]
        public void DocumentFileTest()
        {
            // TODO unit test for the property 'DocumentFile'
        }
        /// <summary>
        /// Test the property 'ShouldEncrypt'
        /// </summary>
        [Test]
        public void ShouldEncryptTest()
        {
            // TODO unit test for the property 'ShouldEncrypt'
        }

    }

}
