/*
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Obada.Client.Api;
using Obada.Client.Model;
using Obada.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Obada.Client.Test
{
    /// <summary>
    ///  Class for testing GenerateObitDIDResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GenerateObitDIDResponseTests
    {
        // TODO uncomment below to declare an instance variable for GenerateObitDIDResponse
        //private GenerateObitDIDResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GenerateObitDIDResponse
            //instance = new GenerateObitDIDResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GenerateObitDIDResponse
        /// </summary>
        [Test]
        public void GenerateObitDIDResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GenerateObitDIDResponse
            //Assert.IsInstanceOf(typeof(GenerateObitDIDResponse), instance);
        }


        /// <summary>
        /// Test the property 'SerialNumberHash'
        /// </summary>
        [Test]
        public void SerialNumberHashTest()
        {
            // TODO unit test for the property 'SerialNumberHash'
        }
        /// <summary>
        /// Test the property 'Usn'
        /// </summary>
        [Test]
        public void UsnTest()
        {
            // TODO unit test for the property 'Usn'
        }
        /// <summary>
        /// Test the property 'Did'
        /// </summary>
        [Test]
        public void DidTest()
        {
            // TODO unit test for the property 'Did'
        }
        /// <summary>
        /// Test the property 'UsnBase58'
        /// </summary>
        [Test]
        public void UsnBase58Test()
        {
            // TODO unit test for the property 'UsnBase58'
        }

    }

}
