/*
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Obada.Client.Api;
using Obada.Client.Model;
using Obada.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Obada.Client.Test
{
    /// <summary>
    ///  Class for testing GenerateObitChecksumRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GenerateObitChecksumRequestTests
    {
        // TODO uncomment below to declare an instance variable for GenerateObitChecksumRequest
        //private GenerateObitChecksumRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GenerateObitChecksumRequest
            //instance = new GenerateObitChecksumRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GenerateObitChecksumRequest
        /// </summary>
        [Test]
        public void GenerateObitChecksumRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GenerateObitChecksumRequest
            //Assert.IsInstanceOf(typeof(GenerateObitChecksumRequest), instance);
        }


        /// <summary>
        /// Test the property 'Manufacturer'
        /// </summary>
        [Test]
        public void ManufacturerTest()
        {
            // TODO unit test for the property 'Manufacturer'
        }
        /// <summary>
        /// Test the property 'PartNumber'
        /// </summary>
        [Test]
        public void PartNumberTest()
        {
            // TODO unit test for the property 'PartNumber'
        }
        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Test]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }
        /// <summary>
        /// Test the property 'MetadataUri'
        /// </summary>
        [Test]
        public void MetadataUriTest()
        {
            // TODO unit test for the property 'MetadataUri'
        }
        /// <summary>
        /// Test the property 'MetadataUriHash'
        /// </summary>
        [Test]
        public void MetadataUriHashTest()
        {
            // TODO unit test for the property 'MetadataUriHash'
        }
        /// <summary>
        /// Test the property 'TrustAnchorToken'
        /// </summary>
        [Test]
        public void TrustAnchorTokenTest()
        {
            // TODO unit test for the property 'TrustAnchorToken'
        }

    }

}
