/*
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Obada.Client.Api;
using Obada.Client.Model;
using Obada.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Obada.Client.Test
{
    /// <summary>
    ///  Class for testing GenerateObitChecksumResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GenerateObitChecksumResponseTests
    {
        // TODO uncomment below to declare an instance variable for GenerateObitChecksumResponse
        //private GenerateObitChecksumResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GenerateObitChecksumResponse
            //instance = new GenerateObitChecksumResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GenerateObitChecksumResponse
        /// </summary>
        [Test]
        public void GenerateObitChecksumResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GenerateObitChecksumResponse
            //Assert.IsInstanceOf(typeof(GenerateObitChecksumResponse), instance);
        }


        /// <summary>
        /// Test the property 'Checksum'
        /// </summary>
        [Test]
        public void ChecksumTest()
        {
            // TODO unit test for the property 'Checksum'
        }
        /// <summary>
        /// Test the property 'ComputeLog'
        /// </summary>
        [Test]
        public void ComputeLogTest()
        {
            // TODO unit test for the property 'ComputeLog'
        }

    }

}
