/*
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Obada.Client.Api;
using Obada.Client.Model;
using Obada.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Obada.Client.Test
{
    /// <summary>
    ///  Class for testing NewMnemonic
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewMnemonicTests
    {
        // TODO uncomment below to declare an instance variable for NewMnemonic
        //private NewMnemonic instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NewMnemonic
            //instance = new NewMnemonic();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NewMnemonic
        /// </summary>
        [Test]
        public void NewMnemonicInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" NewMnemonic
            //Assert.IsInstanceOf(typeof(NewMnemonic), instance);
        }


        /// <summary>
        /// Test the property 'Mnemonic'
        /// </summary>
        [Test]
        public void MnemonicTest()
        {
            // TODO unit test for the property 'Mnemonic'
        }
        /// <summary>
        /// Test the property 'Force'
        /// </summary>
        [Test]
        public void ForceTest()
        {
            // TODO unit test for the property 'Force'
        }

    }

}
