/*
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Obada.Client.Api;
using Obada.Client.Model;
using Obada.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Obada.Client.Test
{
    /// <summary>
    ///  Class for testing NFT
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NFTTests
    {
        // TODO uncomment below to declare an instance variable for NFT
        //private NFT instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NFT
            //instance = new NFT();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NFT
        /// </summary>
        [Test]
        public void NFTInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" NFT
            //Assert.IsInstanceOf(typeof(NFT), instance);
        }


        /// <summary>
        /// Test the property 'ClassId'
        /// </summary>
        [Test]
        public void ClassIdTest()
        {
            // TODO unit test for the property 'ClassId'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'UriHash'
        /// </summary>
        [Test]
        public void UriHashTest()
        {
            // TODO unit test for the property 'UriHash'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
