/*
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Obada.Client.Api;
using Obada.Client.Model;
using Obada.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Obada.Client.Test
{
    /// <summary>
    ///  Class for testing Obit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ObitTests
    {
        // TODO uncomment below to declare an instance variable for Obit
        //private Obit instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Obit
            //instance = new Obit();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Obit
        /// </summary>
        [Test]
        public void ObitInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Obit
            //Assert.IsInstanceOf(typeof(Obit), instance);
        }


        /// <summary>
        /// Test the property 'Did'
        /// </summary>
        [Test]
        public void DidTest()
        {
            // TODO unit test for the property 'Did'
        }
        /// <summary>
        /// Test the property 'Usn'
        /// </summary>
        [Test]
        public void UsnTest()
        {
            // TODO unit test for the property 'Usn'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Test]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'Manufacturer'
        /// </summary>
        [Test]
        public void ManufacturerTest()
        {
            // TODO unit test for the property 'Manufacturer'
        }
        /// <summary>
        /// Test the property 'PartNumber'
        /// </summary>
        [Test]
        public void PartNumberTest()
        {
            // TODO unit test for the property 'PartNumber'
        }
        /// <summary>
        /// Test the property 'SerialNumberHash'
        /// </summary>
        [Test]
        public void SerialNumberHashTest()
        {
            // TODO unit test for the property 'SerialNumberHash'
        }
        /// <summary>
        /// Test the property 'TrustAnchorToken'
        /// </summary>
        [Test]
        public void TrustAnchorTokenTest()
        {
            // TODO unit test for the property 'TrustAnchorToken'
        }
        /// <summary>
        /// Test the property 'Documents'
        /// </summary>
        [Test]
        public void DocumentsTest()
        {
            // TODO unit test for the property 'Documents'
        }
        /// <summary>
        /// Test the property 'Checksum'
        /// </summary>
        [Test]
        public void ChecksumTest()
        {
            // TODO unit test for the property 'Checksum'
        }

    }

}
