/*
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using RestSharp;
using Obada.Client.Client;
using Obada.Client.Model;

namespace Obada.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUtilsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Generates Obit checksum
        /// </summary>
        /// <remarks>
        /// Generates Obit checksum and provides a log of generation details
        /// </remarks>
        /// <exception cref="Obada.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateObitChecksumRequest"> (optional)</param>
        /// <returns>GenerateObitChecksumResponse</returns>
        GenerateObitChecksumResponse GenerateChecksum (GenerateObitChecksumRequest generateObitChecksumRequest = default(GenerateObitChecksumRequest));

        /// <summary>
        /// Generates Obit checksum
        /// </summary>
        /// <remarks>
        /// Generates Obit checksum and provides a log of generation details
        /// </remarks>
        /// <exception cref="Obada.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateObitChecksumRequest"> (optional)</param>
        /// <returns>ApiResponse of GenerateObitChecksumResponse</returns>
        ApiResponse<GenerateObitChecksumResponse> GenerateChecksumWithHttpInfo (GenerateObitChecksumRequest generateObitChecksumRequest = default(GenerateObitChecksumRequest));
        /// <summary>
        /// Generate Obit DID
        /// </summary>
        /// <remarks>
        /// Returns the Obit DID for a given device_id, part_number and serial_number input.
        /// </remarks>
        /// <exception cref="Obada.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateObitDIDRequest"> (optional)</param>
        /// <returns>GenerateObitDIDResponse</returns>
        GenerateObitDIDResponse GenerateDID (GenerateObitDIDRequest generateObitDIDRequest = default(GenerateObitDIDRequest));

        /// <summary>
        /// Generate Obit DID
        /// </summary>
        /// <remarks>
        /// Returns the Obit DID for a given device_id, part_number and serial_number input.
        /// </remarks>
        /// <exception cref="Obada.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateObitDIDRequest"> (optional)</param>
        /// <returns>ApiResponse of GenerateObitDIDResponse</returns>
        ApiResponse<GenerateObitDIDResponse> GenerateDIDWithHttpInfo (GenerateObitDIDRequest generateObitDIDRequest = default(GenerateObitDIDRequest));
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Generates Obit checksum
        /// </summary>
        /// <remarks>
        /// Generates Obit checksum and provides a log of generation details
        /// </remarks>
        /// <exception cref="Obada.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateObitChecksumRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of GenerateObitChecksumResponse</returns>
        System.Threading.Tasks.Task<GenerateObitChecksumResponse> GenerateChecksumAsync (GenerateObitChecksumRequest generateObitChecksumRequest = default(GenerateObitChecksumRequest), CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Generates Obit checksum
        /// </summary>
        /// <remarks>
        /// Generates Obit checksum and provides a log of generation details
        /// </remarks>
        /// <exception cref="Obada.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateObitChecksumRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (GenerateObitChecksumResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GenerateObitChecksumResponse>> GenerateChecksumWithHttpInfoAsync (GenerateObitChecksumRequest generateObitChecksumRequest = default(GenerateObitChecksumRequest), CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Generate Obit DID
        /// </summary>
        /// <remarks>
        /// Returns the Obit DID for a given device_id, part_number and serial_number input.
        /// </remarks>
        /// <exception cref="Obada.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateObitDIDRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of GenerateObitDIDResponse</returns>
        System.Threading.Tasks.Task<GenerateObitDIDResponse> GenerateDIDAsync (GenerateObitDIDRequest generateObitDIDRequest = default(GenerateObitDIDRequest), CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Generate Obit DID
        /// </summary>
        /// <remarks>
        /// Returns the Obit DID for a given device_id, part_number and serial_number input.
        /// </remarks>
        /// <exception cref="Obada.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateObitDIDRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (GenerateObitDIDResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GenerateObitDIDResponse>> GenerateDIDWithHttpInfoAsync (GenerateObitDIDRequest generateObitDIDRequest = default(GenerateObitDIDRequest), CancellationToken cancellationToken = default(CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UtilsApi : IUtilsApi
    {
        private Obada.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UtilsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UtilsApi(String basePath)
        {
            this.Configuration = new Obada.Client.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Obada.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UtilsApi"/> class
        /// </summary>
        /// <returns></returns>
        public UtilsApi()
        {
            this.Configuration = Obada.Client.Client.Configuration.Default;

            ExceptionFactory = Obada.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UtilsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UtilsApi(Obada.Client.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Obada.Client.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Obada.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Obada.Client.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Obada.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Generates Obit checksum Generates Obit checksum and provides a log of generation details
        /// </summary>
        /// <exception cref="Obada.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateObitChecksumRequest"> (optional)</param>
        /// <returns>GenerateObitChecksumResponse</returns>
        public GenerateObitChecksumResponse GenerateChecksum (GenerateObitChecksumRequest generateObitChecksumRequest = default(GenerateObitChecksumRequest))
        {
             ApiResponse<GenerateObitChecksumResponse> localVarResponse = GenerateChecksumWithHttpInfo(generateObitChecksumRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Generates Obit checksum Generates Obit checksum and provides a log of generation details
        /// </summary>
        /// <exception cref="Obada.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateObitChecksumRequest"> (optional)</param>
        /// <returns>ApiResponse of GenerateObitChecksumResponse</returns>
        public ApiResponse<GenerateObitChecksumResponse> GenerateChecksumWithHttpInfo (GenerateObitChecksumRequest generateObitChecksumRequest = default(GenerateObitChecksumRequest))
        {

            var localVarPath = "/obit/checksum";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (generateObitChecksumRequest != null && generateObitChecksumRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(generateObitChecksumRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = generateObitChecksumRequest; // byte array
            }

            // authentication (bearerAuth) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GenerateChecksum", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GenerateObitChecksumResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GenerateObitChecksumResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GenerateObitChecksumResponse)));
        }

        /// <summary>
        /// Generates Obit checksum Generates Obit checksum and provides a log of generation details
        /// </summary>
        /// <exception cref="Obada.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateObitChecksumRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of GenerateObitChecksumResponse</returns>
        public async System.Threading.Tasks.Task<GenerateObitChecksumResponse> GenerateChecksumAsync (GenerateObitChecksumRequest generateObitChecksumRequest = default(GenerateObitChecksumRequest), CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<GenerateObitChecksumResponse> localVarResponse = await GenerateChecksumWithHttpInfoAsync(generateObitChecksumRequest, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Generates Obit checksum Generates Obit checksum and provides a log of generation details
        /// </summary>
        /// <exception cref="Obada.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateObitChecksumRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (GenerateObitChecksumResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GenerateObitChecksumResponse>> GenerateChecksumWithHttpInfoAsync (GenerateObitChecksumRequest generateObitChecksumRequest = default(GenerateObitChecksumRequest), CancellationToken cancellationToken = default(CancellationToken))
        {

            var localVarPath = "/obit/checksum";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (generateObitChecksumRequest != null && generateObitChecksumRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(generateObitChecksumRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = generateObitChecksumRequest; // byte array
            }

            // authentication (bearerAuth) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GenerateChecksum", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GenerateObitChecksumResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GenerateObitChecksumResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GenerateObitChecksumResponse)));
        }

        /// <summary>
        /// Generate Obit DID Returns the Obit DID for a given device_id, part_number and serial_number input.
        /// </summary>
        /// <exception cref="Obada.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateObitDIDRequest"> (optional)</param>
        /// <returns>GenerateObitDIDResponse</returns>
        public GenerateObitDIDResponse GenerateDID (GenerateObitDIDRequest generateObitDIDRequest = default(GenerateObitDIDRequest))
        {
             ApiResponse<GenerateObitDIDResponse> localVarResponse = GenerateDIDWithHttpInfo(generateObitDIDRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Generate Obit DID Returns the Obit DID for a given device_id, part_number and serial_number input.
        /// </summary>
        /// <exception cref="Obada.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateObitDIDRequest"> (optional)</param>
        /// <returns>ApiResponse of GenerateObitDIDResponse</returns>
        public ApiResponse<GenerateObitDIDResponse> GenerateDIDWithHttpInfo (GenerateObitDIDRequest generateObitDIDRequest = default(GenerateObitDIDRequest))
        {

            var localVarPath = "/obit/did";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (generateObitDIDRequest != null && generateObitDIDRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(generateObitDIDRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = generateObitDIDRequest; // byte array
            }

            // authentication (bearerAuth) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GenerateDID", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GenerateObitDIDResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GenerateObitDIDResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GenerateObitDIDResponse)));
        }

        /// <summary>
        /// Generate Obit DID Returns the Obit DID for a given device_id, part_number and serial_number input.
        /// </summary>
        /// <exception cref="Obada.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateObitDIDRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of GenerateObitDIDResponse</returns>
        public async System.Threading.Tasks.Task<GenerateObitDIDResponse> GenerateDIDAsync (GenerateObitDIDRequest generateObitDIDRequest = default(GenerateObitDIDRequest), CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<GenerateObitDIDResponse> localVarResponse = await GenerateDIDWithHttpInfoAsync(generateObitDIDRequest, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Generate Obit DID Returns the Obit DID for a given device_id, part_number and serial_number input.
        /// </summary>
        /// <exception cref="Obada.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateObitDIDRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (GenerateObitDIDResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GenerateObitDIDResponse>> GenerateDIDWithHttpInfoAsync (GenerateObitDIDRequest generateObitDIDRequest = default(GenerateObitDIDRequest), CancellationToken cancellationToken = default(CancellationToken))
        {

            var localVarPath = "/obit/did";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (generateObitDIDRequest != null && generateObitDIDRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(generateObitDIDRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = generateObitDIDRequest; // byte array
            }

            // authentication (bearerAuth) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GenerateDID", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GenerateObitDIDResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GenerateObitDIDResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GenerateObitDIDResponse)));
        }

    }
}
