/* 
 * OBADA Client Helper API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ObitDid
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ObitDidTests
    {
        // TODO uncomment below to declare an instance variable for ObitDid
        //private ObitDid instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ObitDid
            //instance = new ObitDid();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ObitDid
        /// </summary>
        [Test]
        public void ObitDidInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ObitDid
            //Assert.IsInstanceOf(typeof(ObitDid), instance);
        }


        /// <summary>
        /// Test the property '_ObitDid'
        /// </summary>
        [Test]
        public void _ObitDidTest()
        {
            // TODO unit test for the property '_ObitDid'
        }

    }

}
